[package]
name = "bevy_la_mesa"
version = "0.0.9"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Build card games with Bevy"
keywords = ["cards", "tabletop", "bevy"]
repository = "https://github.com/stillonearth/bevy_la_mesa"

[dependencies]
bevy = "0.14"
bevy_mod_picking = "0.20"
bevy_tweening = "0.11"
rand = "0.8"

[dev-dependencies]
bevy-inspector-egui = "0.27.0"

[lints.clippy]
too_many_arguments = "allow"
type_complexity = "allow"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
